version: "3.9"

services:
  web:
    build: .
    command: hypercorn app.main:app --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host
      - DB_PORT=port
      - DB_USER=user
      - DB_PASS=pass

