version: "3.9"

services:
  web:
    build: .
    command: hypercorn app.main:app --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - TRINO_HOST=host
      - TRINO_PORT=port
      - TRINO_USER=user
      - TRINO_PASS=pass
      - LOGGING_NAME=app_name
      - X_API_KEY=KjtUaK1NrTrVG6wARGL0wt0V5iVgGmRH
      - IS_VIRTUAL_HOST=intds4.test.apimanagement.us10.hana.ondemand.com
      - IS_VIRTUAL_PORT=443

